format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$nodejs\
$python\
$rust\
$nix_shell\
$cmd_duration\
$time\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "local"

